-- ─────────────────────────────────────────────────────────────────────────────
-- payment_tests — registro de pruebas de pago (SOLO DESARROLLO)
--
-- Guarda cada prueba hecha en la página /lab-pagos: método, tarjeta, escenario
-- esperado, estado real devuelto por Izipay, resultado y detalle. Se muestra en la
-- pestaña "Tests de pago" del panel admin para corroborar que todo funciona.
--
-- ⚠️ NO aplicar en PRODUCCIÓN. Solo en el proyecto de desarrollo.
-- IDEMPOTENTE: create table if not exists + drop/create policies.
-- ─────────────────────────────────────────────────────────────────────────────

begin;

create table if not exists public.payment_tests (
  id            bigint generated by default as identity primary key,
  created_at    timestamptz not null default now(),
  metodo        text,                 -- "Visa", "Mastercard", "Yape", etc.
  tarjeta       text,                 -- etiqueta/PAN de prueba usado
  escenario     text,                 -- "Aceptado" | "Rechazado" | "3DS" ...
  order_status  text,                 -- lo que devolvió Izipay: PAID / UNPAID / ''
  resultado     text,                 -- "exito" | "fallo"
  detalle       text,                 -- mensaje / código de error
  monto         numeric
);

alter table public.payment_tests enable row level security;

-- Insertar: lo hace la página /lab-pagos (puede no haber sesión). Tabla de prueba
-- sin datos sensibles → permitimos insertar a anon/authenticated.
drop policy if exists payment_tests_insert on public.payment_tests;
create policy payment_tests_insert on public.payment_tests
  for insert to anon, authenticated
  with check (true);

-- Leer: solo administradores (la pestaña del dashboard).
drop policy if exists payment_tests_admin_select on public.payment_tests;
create policy payment_tests_admin_select on public.payment_tests
  for select to authenticated
  using (public.is_admin());

-- Borrar (botón "Limpiar registros" del admin): solo administradores.
drop policy if exists payment_tests_admin_delete on public.payment_tests;
create policy payment_tests_admin_delete on public.payment_tests
  for delete to authenticated
  using (public.is_admin());

commit;
